### ISSUE TITLE
'strcpy_P' was not declared in this scope

### ISSUE THREAD

**Issue by uncodead** [rjwats/esp8266-react#37]
When trying to compile for the first time I get the error below:

![image](https://user-images.githubusercontent.com/181846/60066644-2a69e580-96de-11e9-9a6f-087306287aaf.png)

have you face this problem?

**Comment by rjwats** [comment]
I believe the only errors i have seen with the time library were due to [this issue](https://github.com/rjwats/esp8266-react/issues/27) with the time library, which was resolved in the master branch recently.

I will try a fresh build this evening to see if I get the error. I take it you are building under Windows?

**Comment by uncodead** [comment]
I uninstalled platformio and refreshed my workspace and the error disappear. Thanks

**Comment by fkeller234** [comment]
I'm having the same problem, I made the reinstallation and it didn't solve the problem!
Did you find a solution?
